switch to chi v4

diff --git a/backend/vendor/github.com/go-chi/chi/.travis.yml b/backend/vendor/github.com/go-chi/chi/.travis.yml
--- a/backend/vendor/github.com/go-chi/chi/.travis.yml
+++ b/backend/vendor/github.com/go-chi/chi/.travis.yml
@@ -1,18 +1,18 @@
 language: go
 
 go:
-  - 1.7.x
-  - 1.8.x
-  - 1.9.x
-
-install:
-  - go get -u golang.org/x/tools/cmd/goimports
-  - go get -u github.com/golang/lint/golint
+  - 1.10.x
+  - 1.11.x
+  - 1.12.x
 
 script:
   - go get -d -t ./...
   - go vet ./...
-  - golint ./...
   - go test ./...
   - >
-    goimports -d -e ./ | grep '.*' && { echo; echo "Aborting due to non-empty goimports output."; exit 1; } || :
+    go_version=$(go version);
+    if [ ${go_version:13:4} = "1.12" ]; then
+      go get -u golang.org/x/tools/cmd/goimports;
+      goimports -d -e ./ | grep '.*' && { echo; echo "Aborting due to non-empty goimports output."; exit 1; } || :;
+    fi
+
